import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { fetchRandomMoviesWithBudget, type Difficulty } from '@/lib/tmdb/fetchMovies'
import type { Database } from '@/lib/supabase/database.types'

type GameRow = Database['public']['Tables']['games']['Row']
type PlayerRow = Database['public']['Tables']['players']['Row']

export const dynamic = 'force-dynamic'

export async function POST(request: Request) {
  if (!process.env.TMDB_API_READ_TOKEN) {
    return NextResponse.json({ error: 'TMDB_API_READ_TOKEN not configured' }, { status: 500 })
  }

  const body = await request.json().catch(() => ({}))
  const mode: 'solo' | 'multiplayer' = body.mode === 'multiplayer' ? 'multiplayer' : 'solo'
  const playerName: string =
    typeof body.playerName === 'string' && body.playerName.trim() ? body.playerName.trim() : 'Joueur'

  // ── Paramètres de partie (validés / repliés sur des valeurs sûres) ──
  const rounds = [3, 5, 10].includes(Number(body.rounds)) ? Number(body.rounds) : 5
  const timer = [0, 15, 30, 60].includes(Number(body.timer)) ? Number(body.timer) : 30
  const difficulty: Difficulty = (['all', 'popular', 'recent', 'classics'] as const).includes(
    body.difficulty,
  )
    ? body.difficulty
    : 'all'
  const genre = typeof body.genre === 'string' ? body.genre : 'all'

  try {
    const db = createClient() as any

    const movies = await fetchRandomMoviesWithBudget(rounds, { genre, difficulty })
    if (movies.length < rounds) {
      return NextResponse.json(
        { error: 'Not enough movies for these settings. Try a broader genre/difficulty.' },
        { status: 503 },
      )
    }

    const moviesUpsert = await db.from('movies').upsert(
      movies.map((m) => ({
        id: m.id,
        title: m.title,
        title_fr: m.title_fr,
        year: m.year,
        director: m.director,
        cast_list: m.cast_list,
        poster_path: m.poster_path,
        budget: m.budget,
        genres: m.genres,
        overview: m.overview,
        overview_fr: m.overview_fr,
      })),
      { onConflict: 'id' },
    ) as { error: Error | null }

    if (moviesUpsert.error) {
      console.error('Movies upsert error:', moviesUpsert.error)
      return NextResponse.json({ error: 'Failed to save movies' }, { status: 500 })
    }

    // code intentionally omitted — generated by the DB trigger on INSERT
    const gameInsert = await db
      .from('games')
      .insert({
        mode,
        status: mode === 'solo' ? 'playing' : 'waiting',
        movie_ids: movies.map((m) => m.id),
        current_round: 1,
        timer_seconds: timer,
        difficulty,
        genre,
        locale: 'fr',
      })
      .select()
      .single() as { data: GameRow | null; error: Error | null }

    if (gameInsert.error || !gameInsert.data) {
      console.error('Game create error:', gameInsert.error)
      return NextResponse.json({ error: 'Failed to create game' }, { status: 500 })
    }
    const game = gameInsert.data

    const playerInsert = await db
      .from('players')
      .insert({ game_id: game.id, name: playerName, is_host: true, total_score: 0 })
      .select()
      .single() as { data: PlayerRow | null; error: Error | null }

    if (playerInsert.error || !playerInsert.data) {
      console.error('Player create error:', playerInsert.error)
      return NextResponse.json({ error: 'Failed to create player' }, { status: 500 })
    }
    const player = playerInsert.data

    // Strip budget — revealed only after each guess
    const moviesForClient = movies.map((m) => ({
      id: m.id,
      title: m.title,
      title_fr: m.title_fr,
      year: m.year,
      director: m.director,
      cast_list: m.cast_list,
      poster_path: m.poster_path,
      poster_url: m.poster_url,
      genres: m.genres,
      overview: m.overview,
      overview_fr: m.overview_fr,
    }))

    return NextResponse.json({
      gameId: game.id,
      playerId: player.id,
      gameCode: game.code,
      timerSeconds: timer,
      movies: moviesForClient,
    })
  } catch (err) {
    console.error('Create game error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
